apiVersion: v1
kind: Service
metadata:
  name: two-containers-service
spec:
  type: ClusterIP
  selector:
    app: two-containers
  ports:
  - name: http1
    protocol: TCP
    port: 80
  - name: http2
    protocol: TCP
    port: 6800
  - name: http3
    protocol: TCP
    port: 6880