apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  - name: nginx
    image: dplsming/nginx-fileserver:1.0
    ports:
      - containerPort: 80
    volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html/files 

  - name: aria2ng-downloader
    image: dplsming/aria2ng-downloader:1.0
    ports:
      - containerPort: 6800
      - containerPort: 6880
    volumeMounts:
      - name: shared-data
        mountPath: /data